# Neural Network Programming – Deep Learning with PyTorch

Link to syllabus: http://deeplizard.com/learn/video/v5cngxo4mIg

# PyTorch Explained - Python Deep Learning Neural Network API

Link: http://deeplizard.com/learn/video/iTKbyFh-7GM

# PyTorch Install – Quick and Easy

Link: http://deeplizard.com/learn/video/UWlFM0R_x6I

## Verify the PyTorch install

In [1]:
import torch

In [2]:
print(torch.__version__)

1.5.0


In [3]:
import torchvision

In [4]:
print(torchvision.__version__)

0.6.0


In [5]:
torch.cuda.is_available()

True

In [6]:
torch.version.cuda

'10.2'

# CUDA Explained – Why Deep Learning Uses GPUs

Link: http://deeplizard.com/learn/video/6stDhEA0wFQ

In [10]:
t = torch.tensor([1,2,3])
t

tensor([1, 2, 3])

In [11]:
t = t.cuda()
t

tensor([1, 2, 3], device='cuda:0')

In [12]:
assert type(t) == torch.Tensor

# Tensors Explained – Data Structures of Deep Learning

## Indexes

In [13]:
a = [1,2,3,4]

In [14]:
a[2]

3

In [15]:
dd = [
[1,2,3],
[4,5,6],
[7,8,9]
]

In [16]:
dd[0][2]

3

In [17]:
assert dd[0][2] == 3

# Rank, Axes, and Shape Explained – Tensors for Deep Learning

Link: https://deeplizard.com/learn/video/AiyK0idr4uM

## Rank

A tensor's *rank* tells us how many indexes are needed to refer to a specific element within the tensor.

## Axes

In [21]:
dd = [
[1,2,3],
[4,5,6],
[7,8,9]
]

In [22]:
dd[0]

[1, 2, 3]

In [23]:
dd[1]

[4, 5, 6]

In [24]:
dd[2]

[7, 8, 9]

The first index of axis 2:

In [25]:
dd[0][0]

1

In [26]:
dd[1][0]

4

In [27]:
dd[2][0]

7

The second index of axis 2:

In [28]:
dd[0][1]

2

In [29]:
dd[1][1]

5

In [30]:
dd[2][1]

8

The third index of axis 3:

In [31]:
dd[0][2]

3

In [32]:
dd[1][2]

6

In [33]:
dd[2][2]

9

## Shape

In [34]:
dd = [
[1,2,3],
[4,5,6],
[7,8,9]
]

In [35]:
t = torch.tensor(dd)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [36]:
type(t)

torch.Tensor

In [37]:
t.shape

torch.Size([3, 3])

A tensor's shape is important:

In [38]:
t.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [39]:
t.reshape(1,9).shape

torch.Size([1, 9])

In [40]:
assert t.reshape(1,9).shape == torch.Size([1,9])

# PyTorch Tensors Explained - Neural Network Programming

Link: https://deeplizard.com/learn/video/Csa5R12jYRg

In [41]:
import torch
import numpy as np

## Tensor class

Tensors in PyTorch are represented using the ```torch.Tensor``` class. 

In [42]:
t = torch.Tensor()
type(t)

torch.Tensor

## Tensor attributes

In [43]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In [44]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

In [45]:
assert t.dtype == torch.float32

## Creation options using data

In [46]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [47]:
torch.Tensor(data)

tensor([1., 2., 3.])

In [48]:
torch.tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [49]:
torch.as_tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [50]:
torch.from_numpy(data)

tensor([1, 2, 3], dtype=torch.int32)

## Creation options without data

In [51]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [52]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [53]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [54]:
torch.rand(2,2)

tensor([[0.3528, 0.7103],
        [0.3428, 0.0408]])

# Creating PyTorch Tensors – Best Options

Link: https://deeplizard.com/learn/video/AglLTlms7HU

In [55]:
import torch
import numpy as np

In [56]:
data = np.array([1,2,3])

In [57]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [58]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)


In [59]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int32
torch.int32
torch.int32


The constructor function used the default dtype.

In [60]:
torch.get_default_dtype()

torch.float32

In [61]:
t1.dtype == torch.get_default_dtype()

True

In [74]:
assert t1.dtype == torch.get_default_dtype()

The factory functions infer the dtype.

In [66]:
torch.tensor(np.array([1,2,3]))

tensor([1, 2, 3], dtype=torch.int32)

In [67]:
torch.tensor(np.array([1.,2.,3.]))

tensor([1., 2., 3.], dtype=torch.float64)

The dtype can be explicitly set.

In [68]:
torch.tensor(np.array([1,2,3]), dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

## Memory: Sharing vs Copying

In [69]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [70]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [71]:
data[0] = 0
data[1] = 0
data[2] = 0

In [72]:
print(t1)
print(t2)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)


In [73]:
print(t3)
print(t4)

tensor([0, 0, 0], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)


# Tensor Operations for Deep Learning

Operations by category:
- Reshaping ops
- Element-wise ops
- Reduction ops
- Access ops


# Reshaping Explained - PyTorch Tensors for Deep Learning

Link: https://deeplizard.com/learn/video/fCVuiW9AFzY

In [65]:
import torch

In [66]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [67]:
t.size()

torch.Size([3, 4])

In [68]:
t.shape

torch.Size([3, 4])

In [69]:
len(t.shape)

2

In [70]:
torch.tensor(t.shape).prod()

tensor(12)

In [71]:
t.numel()

12

In [72]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [73]:
t.reshape(2,6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [74]:
t.reshape(3,4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [75]:
t.reshape(4,3)

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [76]:
t.reshape(6,2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [77]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [78]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

In [79]:
print(t.reshape(1,12))
print(t.reshape(1,12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [80]:
print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [81]:
print(t.reshape(1,12).squeeze().unsqueeze(dim=0))
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [82]:
def flatten(t):
    t = t.reshape(1,-1)
    t = t.squeeze()
    return t

In [83]:
flatten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [84]:
t.reshape(-1)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [85]:
assert flatten(t).shape == t.reshape(-1).shape

# Reshaping Explained - PyTorch Tensors for Deep Learning

Link: https://deeplizard.com/learn/video/fCVuiW9AFzY

### Shape/Size of a tensor

In [87]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [88]:
t.size()

torch.Size([3, 4])

In [89]:
t.shape

torch.Size([3, 4])

In [90]:
len(t.shape)

2

In [91]:
torch.tensor(t.shape).prod()

tensor(12)

In [92]:
t.numel()

12

Since our tensor ```t``` has 12 elements, any reshaping must account for the number of elements (```12```). 

### Reshape/View

In [93]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [94]:
t.reshape(2,6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [95]:
t.reshape(3,4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [96]:
t.reshape(4,3)

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [97]:
t.reshape(6,2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [98]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

Reshaping and changing the rank.

In [99]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

### Squeeze/Unsqueeze

In [100]:
print(t.reshape(1,12))
print(t.reshape(1,12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [101]:
print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [102]:
print(t.reshape(1,12).squeeze().unsqueeze(dim=0))
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


Here is a use case for squeeze:

In [103]:
def flatten(t):
    t = t.reshape(1, -1)
    t = t.squeeze()
    return t

In [104]:
flatten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

### Concantenate two tensors

In [105]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])
t2 = torch.tensor([
    [5,6],
    [7,8]
])

In [106]:
torch.cat((t1, t2), dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [107]:
torch.cat((t1, t2), dim=0).shape

torch.Size([4, 2])

In [108]:
torch.cat((t1, t2), dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [109]:
torch.cat((t1, t2), dim=1).shape

torch.Size([2, 4])

# CNN Flatten Operation Visualized – Tensor Batch Processing for Deep Learning

Link: https://deeplizard.com/learn/video/mFAIBMbACMA

In [110]:
import torch

In [111]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

In [112]:
t = torch.stack((t1,t2,t3))
t.shape

torch.Size([3, 4, 4])

In [113]:
assert t.shape == torch.Size([3,4,4])

In [114]:
t

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

Add the color channel axis so we'll have: `(Batch size, Color channels, Height, Width)`

In [115]:
t = t.reshape(3,1,4,4)
t

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [116]:
t[0]

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [117]:
t[0][0]

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [118]:
t[0][0][0]

tensor([1, 1, 1, 1])

In [119]:
t[0][0][0][0]

tensor(1)

### Shout outs for alternative implementations of the `flatten()`s function!

In [120]:
t.reshape(1,-1)[0] # Thank you Mick!

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [121]:
t.reshape(-1) # Thank you Aamir!

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [122]:
t.view(t.numel()) # Thank you Ulm!

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [123]:
t.flatten() # Thank you PyTorch!

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

### Only Flatten the last 3 axes

In [124]:
t.flatten(start_dim=1).shape

torch.Size([3, 16])

In [125]:
t.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

# Element-wise tensor operations - Deep Learning and Neural Networks

Element-wise means that we operate on corresponding elements.  
Two elements are said to corresponding if the two elements occupy the same position within the tensor.  
The position is determined by the indexes used to specify a given element.

Link: https://deeplizard.com/learn/video/QscEWm0QTRY

In [126]:
import torch
import numpy as np

In [127]:
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype=torch.float32)

t2 = torch.tensor([
    [9,8],
    [7,6]
], dtype=torch.float32)

In [128]:
# Example from the first axis
t1[0]

tensor([1., 2.])

In [129]:
# Example from the second axis
t1[0][0]

tensor(1.)

In [130]:
t1[0][0]

tensor(1.)

In [131]:
t2[0][0]

tensor(9.)

### Addition is an element-wise operation

In [132]:
t1 + t2

tensor([[10., 10.],
        [10., 10.]])

### Arithmetic operations are element-wise operations

Let's see how we can add scalar values to tensors:

In [133]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [134]:
t1 - 2

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [135]:
t1 * 2

tensor([[2., 4.],
        [6., 8.]])

In [136]:
t1 / 2

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [137]:
t1.add(2)

tensor([[3., 4.],
        [5., 6.]])

In [138]:
t1.sub(2)

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [139]:
t1.mul(2)

tensor([[2., 4.],
        [6., 8.]])

In [140]:
t1.div(2)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

These examples make it look like element-wise means *for each element*.  
However, this is misleading.  
A concept called broadcasting is being used here.

#### Broadcasting tensors

What is really happening in ```t1 + 2``` is that the scaler ```2``` is being broadcasted to the shape of ```t1```.  
This can be done using Numpy like this:

In [141]:
np.broadcast_to(2, t1.shape)

array([[2, 2],
       [2, 2]])

After the new tensor is created from the broadcast operation, the element-wise addition is performed.  
So this:

In [142]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

is really this:

In [143]:
t1 + torch.tensor(
    np.broadcast_to(2, t1.shape)
    ,dtype=torch.float32
)

tensor([[3., 4.],
        [5., 6.]])

Trickier example:

In [144]:
t1 = torch.tensor([
    [1,1],
    [1,1]
], dtype=torch.float32)

t2 = torch.tensor([2,4], dtype=torch.float32)

In [145]:
# t1 + t2 ???????

In [146]:
t1.shape

torch.Size([2, 2])

In [147]:
t2.shape

torch.Size([2])

In [148]:
np.broadcast_to(t2.numpy(), t1.shape)

array([[2., 4.],
       [2., 4.]], dtype=float32)

In [149]:
t1 + t2

tensor([[3., 5.],
        [3., 5.]])

See this one for a deeper discussion on broadcasting: http://deeplizard.com/learn/video/6_33ulFDuCg

### Element-wise comparison operations

In [150]:
import torch

In [151]:
t = torch.tensor([
    [0,5,7],
    [6,0,7],
    [0,8,0]
], dtype=torch.float32)

In [152]:
t.eq(0)

tensor([[ True, False, False],
        [False,  True, False],
        [ True, False,  True]])

In [153]:
t.ge(0)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [154]:
t.gt(0)

tensor([[False,  True,  True],
        [ True, False,  True],
        [False,  True, False]])

In [155]:
t.lt(0)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [156]:
t.le(7)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

Thinking about these types of operations from a broadcasting perspective, we can see that ```t.le(7)``` is the same thing as:

In [157]:
t <= torch.tensor(
    np.broadcast_to(7, t.shape)
    ,dtype=torch.float32
)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

and this:

In [158]:
t <= torch.tensor([
    [7,7,7],
    [7,7,7],
    [7,7,7]
], dtype=torch.float32)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

### [BC-BREAKING] Changed tensor comparison return type from uint8 to bool #21113

Relevant links:  
https://github.com/pytorch/pytorch/pull/21113  
https://github.com/pytorch/pytorch/releases/tag/v1.2.0

This change was introduced in PyTorch version 1.2.0.  
Unit test for this change is below:

In [159]:
# Unit test
t1 = torch.tensor([
    [0,5,7],
    [6,0,7],
    [0,8,0]
], dtype=torch.float32)

t2 = torch.tensor([
    [7,7,7],
    [7,7,7],
    [7,7,7]
], dtype=torch.float32)

t3 = t1 <= t2

assert t3.dtype == torch.bool

### Element-wise operations using functions

In [160]:
t.abs()

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])

In [161]:
t.sqrt()

tensor([[0.0000, 2.2361, 2.6458],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])

In [162]:
t.neg()

tensor([[-0., -5., -7.],
        [-6., -0., -7.],
        [-0., -8., -0.]])

In [163]:
torch.tensor([-0.0])

tensor([-0.])

In [164]:
torch.tensor([0])

tensor([0])

In [165]:
torch.tensor([0]).neg()

tensor([0])

In [166]:
-0.0

-0.0

In [167]:
t.neg().abs()

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])

# Argmax and Reduction Ops - Tensors for Deep Learning

Link: https://deeplizard.com/learn/video/K3lX3Cltt4c

In [168]:
import torch
import numpy as np

A tensor *reduction operation* is an operation that reduces the number of elements contained within a given tensor. 

Suppose we have the following tensor:

In [169]:
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
], dtype=torch.float32)

Observe that the sum function returns the sum of all the elements in the tensor:

In [170]:
t.sum()

tensor(8.)

In [171]:
t.numel()

9

In [172]:
t.sum().numel()

1

In [173]:
t.sum().numel() < t.numel()

True

In [174]:
assert t.sum().numel() < t.numel()

Therefore, we can conclude that the ```sum()``` function is a reduction operation.

### Common reduction operations

In [175]:
t.sum()

tensor(8.)

In [176]:
t.prod()

tensor(0.)

In [177]:
t.mean()

tensor(0.8889)

In [178]:
t.std()

tensor(1.1667)

### Reduce specific axes

In [179]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [180]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [181]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

Element-wise opeartions are in play here:

In [182]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [183]:
t[0]

tensor([1., 1., 1., 1.])

In [184]:
t[1]

tensor([2., 2., 2., 2.])

In [185]:
t[2]

tensor([3., 3., 3., 3.])

In [186]:
t[0] + t[1] + t[2]

tensor([6., 6., 6., 6.])

Three groups of four:

In [187]:
t[0].sum()

tensor(4.)

In [188]:
t[1].sum()

tensor(8.)

In [189]:
t[2].sum()

tensor(12.)

In [190]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

### Max/Argmax

In [191]:
t = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
], dtype=torch.float32)

In [192]:
t.max()

tensor(5.)

In [193]:
t.argmax()

tensor(11)

In [194]:
t.flatten()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

If we specify a dimension, the ```max()``` function will return two tensors.  

In [195]:
t.max(dim=0)

torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))

In [196]:
t.argmax(dim=0)

tensor([2, 1, 1, 2])

In [197]:
t.max(dim=1)

torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 2, 3]))

In [198]:
t.argmax(dim=1)

tensor([3, 2, 3])

## Accessing operations

In [199]:
t = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype=torch.float32) ## Accessing operations

In [200]:
t.mean()

tensor(5.)

In [201]:
t.mean().item()

5.0

In [202]:
t.mean(dim=0).tolist()

[4.0, 5.0, 6.0]

In [203]:
t.mean(dim=0).numpy()

array([4., 5., 6.], dtype=float32)

In [204]:
assert t.mean().item() == 5

# THE END OF PART 1

Link to the start of part 2: https://deeplizard.com/learn/video/EqpzfvxBx30